using System;
using System.IO;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

/// <summary>
/// Editor-side system that scans all loaded <see cref="Component"/> types for
/// <see cref="EntityAttribute"/> and auto-generates / updates .prefab files for them.
///
/// Runs on every hotload so changes to attributes are reflected immediately
/// without any manual prefab editing.
///
/// WHAT GETS GENERATED:
///   For a component tagged [Entity("item_healthvial"), PropModel("models/...")]
///   the generator writes Assets/prefabs/entities/item_healthvial.prefab containing:
///     - The component itself
///     - Sandbox.Prop  (if [PropModel] is present)
///
/// ORPHAN CLEANUP:
///   Tracks generated classnames via Assets/prefabs/entities/.entity_manifest.json.
///   Any prefab in the manifest whose [Entity] type no longer exists is deleted.
///
/// CONFLICT SAFETY:
///   Prefabs NOT listed in the manifest (i.e. hand-crafted ones) are never touched.
/// </summary>
public static class EntityPrefabGenerator
{
	private const string PrefabSubdir  = "prefabs/entities";
	private const string ManifestName  = ".entity_manifest.json";
	private const string GeneratorTag  = "xgk_autogenerated";

	// -------------------------------------------------------------------------
	// Hotload hook
	// -------------------------------------------------------------------------

	[EditorEvent.Hotload]
	public static void OnHotload() => Run();

	[Menu( "Editor", "XenGameKit/Regenerate Entity Prefabs" )]
	public static void RunManual()
	{
		Run();
		Log.Info( "[EntityPrefabGenerator] Manual run complete." );
	}

	// -------------------------------------------------------------------------
	// Core
	// -------------------------------------------------------------------------

	public static void Run()
	{
		var assetsPath = Sandbox.Project.Current.GetAssetsPath();
		var prefabDir  = Path.Combine( assetsPath, PrefabSubdir );
		var manifestPath = Path.Combine( prefabDir, ManifestName );

		Directory.CreateDirectory( prefabDir );

		var manifest  = LoadManifest( manifestPath );
		var generated = new HashSet<string>( StringComparer.OrdinalIgnoreCase );

		foreach ( var info in FindEntityTypes() )
		{
			var classname  = info.Entity.Classname;
			var prefabPath = Path.Combine( prefabDir, classname + ".prefab" );

			generated.Add( classname );

			// Don't touch hand-authored prefabs we don't own
			if ( File.Exists( prefabPath ) && !manifest.Contains( classname ) )
			{
				Log.Warning( $"[EntityPrefabGenerator] Skipping '{classname}' — prefab exists but wasn't generated here. Delete it manually to hand it over." );
				continue;
			}

			var json = BuildPrefabJson( info );
			File.WriteAllText( prefabPath, json, Encoding.UTF8 );
			// Register the new/updated file with the asset system so it shows up immediately
			AssetSystem.RegisterFile( prefabPath );
			Log.Info( $"[EntityPrefabGenerator] Generated {classname}.prefab" );
		}

		// Delete orphans — classnames we generated that no longer have a type
		foreach ( var classname in manifest )
		{
			if ( generated.Contains( classname ) ) continue;

			var orphanPath = Path.Combine( prefabDir, classname + ".prefab" );
			if ( File.Exists( orphanPath ) )
			{
				File.Delete( orphanPath );
				Log.Info( $"[EntityPrefabGenerator] Deleted orphaned prefab: {classname}.prefab" );
			}
		}

		SaveManifest( manifestPath, generated );
	}

	// -------------------------------------------------------------------------
	// Type scanning
	// -------------------------------------------------------------------------

	private record EntityTypeInfo(
		TypeDescription         TypeDesc,
		EntityAttribute         Entity,
		PropModelAttribute      PropModel,
		TriggerBoxAttribute     TriggerBox,
		string                  Title,
		string                  Category,
		string                  Icon
	);

	private static IEnumerable<EntityTypeInfo> FindEntityTypes()
	{
		foreach ( var typeDesc in EditorTypeLibrary.GetTypes<Component>() )
		{
			var entityAttr = typeDesc.GetAttribute<EntityAttribute>();
			if ( entityAttr is null ) continue;

			// Read Title / Category via TypeLibrary (same API the scene browser uses)
			var targetType = typeDesc.TargetType;
			var titleAttr  = targetType is not null
				? TypeLibrary.GetAttribute<TitleAttribute>( targetType )
				: null;
			var catAttr = targetType is not null
				? TypeLibrary.GetAttribute<CategoryAttribute>( targetType )
				: null;
			var iconAttr = targetType is not null
				? TypeLibrary.GetAttribute<IconAttribute>( targetType )
				: null;

			yield return new EntityTypeInfo(
				typeDesc,
				entityAttr,
				typeDesc.GetAttribute<PropModelAttribute>(),
				typeDesc.GetAttribute<TriggerBoxAttribute>(),
				titleAttr?.Value  ?? typeDesc.Name,
				catAttr?.Value ?? "Entities",
				iconAttr?.Value
			);
		}
	}

	// -------------------------------------------------------------------------
	// Prefab JSON builder
	// -------------------------------------------------------------------------

	private static string BuildPrefabJson( EntityTypeInfo info )
	{
		var classname = info.Entity.Classname;
		var components = new JsonArray();

		// 1. The user's component — defaults come from the type, no need to serialize them here
		components.Add( MakeComponentNode( info.TypeDesc.FullName ?? info.TypeDesc.Name ) );

		// 2. Sandbox.Prop — only when [PropModel] is set
		if ( info.PropModel is not null )
		{
			var prop = MakeComponentNode( "Sandbox.Prop" );
			prop["Model"]            = info.PropModel.ModelPath;
			prop["IsStatic"]         = false;
			prop["Health"]           = 0;
			// ulong.MaxValue = all body groups visible — matches what the editor writes
			prop["BodyGroups"]       = 18446744073709551615UL;
			prop["MaterialGroup"]    = null;
			prop["Tint"]             = "1,1,1,1";
			prop["StartAsleep"]      = false;
			prop["OnPropBreak"]      = null;
			prop["OnPropTakeDamage"] = null;
			components.Add( prop );
		}

		// 3. Sandbox.BoxCollider (trigger) — when [TriggerBox] is set
		if ( info.TriggerBox is not null )
		{
			var tb  = info.TriggerBox;
			var col = MakeComponentNode( "Sandbox.BoxCollider" );
			col["Center"]       = $"{tb.CenterX},{tb.CenterY},{tb.CenterZ}";
			col["Scale"]        = $"{tb.SizeX},{tb.SizeY},{tb.SizeZ}";
			col["IsTrigger"]    = true;
			col["Static"]       = false;
			col["ColliderFlags"] = 0;
			col["Elasticity"]   = null;
			col["Friction"]     = null;
			col["RollingResistance"] = null;
			col["Surface"]      = null;
			col["SurfaceVelocity"] = "0,0,0";
			col["OnObjectTriggerEnter"] = null;
			col["OnObjectTriggerExit"]  = null;
			col["OnTriggerEnter"]       = null;
			col["OnTriggerExit"]        = null;
			components.Add( col );
		}

		// MenuPath mirrors the hand-authored pattern: "XenGameKit/<Category>/<Title>"
		var menuPath = $"XenGameKit/{info.Category}/{info.Title}";

		var root = new JsonObject
		{
			["RootObject"] = new JsonObject
			{
				["__guid"]            = Guid.NewGuid().ToString(),
				["__version"]         = 2,
				["Flags"]             = 0,
				["Name"]              = classname,
				["Position"]          = "0,0,0",
				["Rotation"]          = "0,0,0,1",
				["Scale"]             = "1,1,1",
				["Tags"]              = "item",
				["Enabled"]           = true,
				["NetworkMode"]       = 1,
				["NetworkFlags"]      = 0,
				["NetworkOrphaned"]   = 1,
				["NetworkTransmit"]   = true,
				["OwnerTransfer"]     = 1,
				["Components"]        = components,
				["Children"]          = new JsonArray(),
				["__properties"]      = new JsonObject
				{
					["NetworkInterpolation"] = true,
					["TimeScale"]            = 1,
					["WantsSystemScene"]     = true,
					["Metadata"]             = new JsonObject(),
					["NavMesh"] = new JsonObject
					{
						["Enabled"]                = false,
						["IncludeStaticBodies"]    = true,
						["IncludeKeyframedBodies"] = true,
						["EditorAutoUpdate"]       = false,
						["AgentHeight"]            = 64,
						["AgentRadius"]            = 16,
						["AgentStepSize"]          = 18,
						["AgentMaxSlope"]          = 40,
						["ExcludedBodies"]         = "",
						["IncludedBodies"]         = "",
						["DeferGeneration"]        = false,
						["CustomBounds"]           = false,
					},
				},
				["__variables"] = new JsonArray(),
			},
			["ResourceVersion"]     = 2,
			["ShowInMenu"]          = true,
			["MenuPath"]            = menuPath,
			["MenuIcon"]            = info.Icon,
			["DontBreakAsTemplate"] = true,
			// Generator bookkeeping — stripped at compile time, harmless at runtime
			["_xgk_generator"]     = GeneratorTag,
			["_xgk_classname"]     = classname,
			["__references"]       = new JsonArray(),
			["__version"]          = 2,
		};

		return root.ToJsonString( new JsonSerializerOptions { WriteIndented = true } );
	}

	/// <summary>Builds the boilerplate wrapper every component entry needs.</summary>
	private static JsonObject MakeComponentNode( string typeName )
	{
		return new JsonObject
		{
			["__type"]                  = typeName,
			["__guid"]                  = Guid.NewGuid().ToString(),
			["__enabled"]               = true,
			["Flags"]                   = 0,
			["OnComponentDestroy"]      = null,
			["OnComponentDisabled"]     = null,
			["OnComponentEnabled"]      = null,
			["OnComponentFixedUpdate"]  = null,
			["OnComponentStart"]        = null,
			["OnComponentUpdate"]       = null,
		};
	}

	// -------------------------------------------------------------------------
	// Manifest helpers
	// -------------------------------------------------------------------------

	private static HashSet<string> LoadManifest( string path )
	{
		if ( !File.Exists( path ) )
			return new HashSet<string>( StringComparer.OrdinalIgnoreCase );

		try
		{
			var list = JsonSerializer.Deserialize<List<string>>( File.ReadAllText( path ) );
			return new HashSet<string>( list ?? new(), StringComparer.OrdinalIgnoreCase );
		}
		catch
		{
			return new HashSet<string>( StringComparer.OrdinalIgnoreCase );
		}
	}

	private static void SaveManifest( string path, IEnumerable<string> classnames )
	{
		var json = JsonSerializer.Serialize(
			classnames.OrderBy( x => x ).ToList(),
			new JsonSerializerOptions { WriteIndented = true }
		);
		File.WriteAllText( path, json, Encoding.UTF8 );
	}
}
